# Local Secure Credentials

# Salesforce Credentials

salesforce:
  username: "![BsOyxgx6vrZVlfsEwG2jAYjw5599D3FMrbrGGg+HMpQ=]"
  password: "![x/5pPrhyeynkYVDRWd8ddw==]"
  securitytoken: "![WZ9Sl7McuQrRuIrkRRmgQEiv5AdTMN18jDXCGBLsNcA=]"